### ISSUE TITLE
Start with server mode

### ISSUE THREAD

**Issue by jdahm** [emacsfodder/emacs-theme-darktooth#17] opened 2015-09-26 19:14 UTC
I'm having issues starting a server instance with `emacs --daemon` and launching a new frame and even directly with

```
emacsclient -a "" -c $FILE
```

when `(load-file 'darktooth t)` is in `~/.emacs.d/init.el`. With all other themes I've tried the theme is correctly applied on the first frame, but with this theme I get a white frame with some simple black text. It then applies correctly if I disable and load the theme again.

I've tried removing bits of my init file but I haven't found a culprit statement yet. Since all other themes seem to work, I'm not entirely sure it's something on my end. Is anyone else having this issue?

**Comment by jasonm23** [comment] 2015-09-27 00:43
Please try Gruvbox theme, Darktooth inherits much from there.  We can use the diff between themes to bisect the error.

**Comment by jdahm** [comment] 2015-09-27 12:55
OK I've switched to trying with the Gruvbox theme. I created a `~/.emacs.d/init.el` with only the `load-theme` command in it and tried both

```
emacsclient -a "" -c $FILE
```

and

```
emacs -Q --load ~/.emacs.d/init.el --daemon
emacsclient -a "" -c $FILE
```

However both still resulted in the white background with simple black text. For reference, I'm using the version in Debian Jessie (stable)

```
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-07 on trouble, modified by Debian
```

**Comment by jasonm23** [comment] 2015-09-27 13:29
Ok this is good news, I'll review the Gruvbox code as soon as I can.

Please also try building the latest Emacs (from source)

**Comment by jdahm** [comment] 2015-09-29 01:08
Same issue occurs with 25.0.50.1.

**Comment by jasonm23** [comment] 2015-10-25 07:33
@jdahm sorry it took a while for me to get on top of this, I've tested on OSX (Emacs 24.5.1) and Ubuntu 15.10 (Emacs 25.0.x) no issues.

It please try bisecting your .emacs.d. and try to isolate the cause on your end.

**Comment by jasonm23** [comment] 2015-10-25 07:34
Sorry I see that you've already paired down the config to just load theme.

**Comment by jasonm23** [comment] 2015-10-25 07:35
I'll spin up a Debian Jesse to see if it's related

**Comment by jasonm23** [comment] 2015-11-21 14:56
Unable to reproduce :(

**Comment by jasonm23** [comment] 2015-11-21 14:57
Please use GNU Emacs 24.5 (stable) to ensure best compatibility with requirements.

**Comment by jdahm** [comment] 2015-12-17 22:41
I still have issues with this. Tried this again today on a Fedora box with GNU Emacs 24.5.1. When I start with a fresh .emacs.d directory and init.el file only applying the theme and run

$ emacsclient -a "" $FILE

The server starts and the frame applies the theme correctly. If instead I create a GUI instance, starting up the server as well with

$ emacsclient -c -a "" $FILE

then the frame has an entirely white theme, even the modeline.

**Comment by tylerharper** [comment] 2016-04-21 11:38
# The Problem

I was able to duplicate this problem.  I am running this on OSX.

~/.emacs.d/init.el

```
(package-initialize)
(load-theme 'darktooth t)
```

Then you run the following commands in your terminal.

```
emacs --daemon
emacsclient -a '' -c
```

You will then get an emacs frame that looks like this

<img width="602" alt="screen shot 2016-04-21 at 7 19 58 am" src="https://cloud.githubusercontent.com/assets/99212/14707285/e042ddd8-0791-11e6-9699-a0524b75dca4.png">

# The Temporary Work Around

Once you get to the above screen just run `M-x load-theme <enter> darktooth`.  It will load the darktooth theme correctly. You will only have to run this once  per emacs daemon start/restart.

# The Possible Culprit

Darktooth is implemented well. It handles both terminal and graphic displays. That nicety is causing the problem.  It looks like `display-graphics-p` is the culprit. Once I removed the if check to handle terminals everything worked fine.

I did stumble upon a stackoverflow [post](http://stackoverflow.com/questions/7616761/even-when-emacsclient-is-started-in-a-terminal-window-system-is-non-nil) that might be helpful.

**Comment by jasonm23** [comment] 2016-04-23 10:35
So it looks like this is an Emacs bug in that case.

Not sure if it can be fixed easily in the theme.  The terminal check is obviously important. 

 If display number of colors always responds with a useful / correct value that might be a way forward.

Pull request would be well received, I won't be working on a fix for this urgently.

**Comment by larkery** [comment] 2016-07-01 08:10
You could use `(or (display-graphic-p) (and (server-running-p) (getenv "DISPLAY")))` in place of `(display-graphic-p)`. That would probably be an adequate fix, if mildly disappointing.

I do this to make it work

```
(cl-letf (((symbol-function 'display-graphic-p)
             (lambda (&rest r) (getenv "DISPLAY"))))
    (load-theme 'darktooth t))
```

**Comment by jasonm23** [comment] 2016-12-24 05:21
Please try this with 0.3.x 

I'm now using Autothemer which will provide better display based colors (using the defface color-class system)

**Closed as completed** 2016-12-28 09:28 UTC
