### ISSUE TITLE
Elfeed font broken

### ISSUE THREAD

**Issue by AdamFrey** [emacsfodder/emacs-theme-darktooth#34] opened 2016-10-21 23:30 UTC
I upgraded Darktooth recently and now elfeed is pretty unusable:

<img width="953" alt="screen shot 2016-10-21 at 7 12 39 pm" src="https://cloud.githubusercontent.com/assets/465987/19614576/980070b2-97c4-11e6-8f53-2b91ec86859f.png">

Entries are invisible until you hover over them with the cursor. I'm not sure if something changed in darktooth or elfeed or both to make this happen.

**Comment by jasonm23** [comment] 2016-10-22 01:34
The only change related to elfeed directly was merged in a year ago: https://github.com/emacsfodder/emacs-theme-darktooth/pull/15

I'll have a look later.  Are there any steps needed to reproduce the problem or can I just start elfeed?

**Comment by jasonm23** [comment] 2016-10-22 01:37
Please try installing earlier releases too.

https://github.com/emacsfodder/emacs-theme-darktooth/releases

Use `M-x package-install-file` to install directly from a downloaded file.

**Comment by jasonm23** [comment] 2016-10-22 02:02
Hmmm, ok well until now I didn't use elfeed, but after installing checked the elfeed faces, and they've remained unchanged since a year ago.

They would've always looked like this, however they are basically illegible. (That'll teach me to trust a pull requests for packages I don't use.  I do ask for screen shots these days though.)

Anyway, don't waste time loading the old versions, I'll patch this and push the update.

Give me a :+1: or 👎 for this screen grab...

<img width="1386" alt="screen shot 2016-10-22 at 10 01 52 am" src="https://cloud.githubusercontent.com/assets/71587/19616152/92dc3a38-983e-11e6-87c6-7ba55be1e700.png">

**Comment by jasonm23** [comment] 2016-10-22 02:08
BTW if this version looks ok to you, it's v 0.1.58 - I will look at giving it a bit more TLC later on.

**Comment by jasonm23** [comment] 2016-10-22 02:09
Check the next MELPA build cycle to upgrade on there. (both Stable and edge.)

**Comment by jasonm23** [comment] 2016-10-22 14:05
For version 0.1.60

Elfeed

![screen shot 2016-10-22 at 10 04 27 pm](https://cloud.githubusercontent.com/assets/71587/19619891/94181646-98a3-11e6-9132-afb064d7f088.png)

Feed message view

![screen shot 2016-10-22 at 10 04 39 pm](https://cloud.githubusercontent.com/assets/71587/19619892/9ac9cdb8-98a3-11e6-8f7c-61d3df4e9dc4.png)

**Comment by AdamFrey** [comment] 2016-10-22 14:15
That looks great. Thanks so much! 👍

**Closed as completed** 2016-10-22 14:15 UTC
